# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'espc2021-conn'
    subscriptionId: '0b1e6544-da36-4abf-8c92-86a434d5047b'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'espc2021pipeline-rg'
    location: 'West Europe'
    templateLocation: 'URL of the file'
    csmFileLink: 'https://raw.githubusercontent.com/alexandair/espc2021/main/CreateWebApp/azuredeploy.json'
    overrideParameters: '-projectName espc2021'
    deploymentMode: 'Incremental'
    deploymentName: 'DeployPipelineTemplate'